
name: android_cache
version: 0.0.1
language: android
description: Android cache
public: true
tags:
  - android
  - cache
inputs:
  - name: FLOW_ENABLE_CACHE
    editable: true
    options:
      - true=TRUE
      - false=FALSE

- name: ENABLE_GRADLE_CACHE
    editable: true
    desc_cn: "开启gradle缓存"
    desc_en: "Enable gradle cache"
    options:
      - true=TRUE
      - false=FALSE
    default: 'FALSE'

- name: ENABLE_NPM_CACHE
    editable: true
    desc_cn: "开启npm缓存"
    desc_en: "Enable npm cache"
    options:
      - true=TRUE
      - false=FALSE
    default: 'TRUE'    

outputs:
  - name: FLOW_ENABLE_CACHE
script_path: ./run.sh  
  
template: |  
  
  
