
name: android_cache
version: 0.0.1
language: android
description: Android cache
public: true
tags:
  - android
  - cache
inputs:
  - name: FLOW_ENABLE_CACHE
    editable: true
    options:
      - true=TRUE
      - false=FALSE
  - name: ENABLE_GRADLE_CACHE
    editable: true

    options:
      - true=TRUE
      - false=FALSE
    default: 'FALSE'
  - name: ENABLE_NPM_CACHE
    editable: true

    options:
      - true=TRUE
      - false=FALSE
    default: 'TRUE'    
  - name: FLOW_VERSION
    editable: false
  - name: FLOW_PROJECT_ID
    editable: false
outputs:
  - name: FLOW_ENABLE_CACHE
script_path: ./run.sh  
  
template: |  
  
  
