
name: android_cache
version: 0.0.1
language: android
description: "缓存 gradle 或 npm 的安装依赖包，已有缓存时直接使用本地的依赖包，减少下载时间，提高构建效率"
public: true
tags:
  - android
  - cache
  
inputs:
  - name: FLOW_ENABLE_GRADLE_CACHE
    editable: true
    desc_cn: "开启gradle缓存"
    desc_en: "Enable gradle cache"
    category: "switcher"
    default: 'FALSE'

  - name: FLOW_ENABLE_NPM_CACHE
    editable: true
    desc_cn: "开启npm缓存"
    desc_en: "Enable npm cache"
    category: "switcher"
    default: 'FALSE'
    
script_path: ./run.sh  
  
template: |  
  
  
